name: Deploy Container Image to Azure App Service

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: carlosdockerregistrie.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t carlosdockerregistrie.azurecr.io/latest:${{ github.sha }}
        docker push carlosdockerregistrie.azurecr.io/latest:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'PruebaDocker2'
        images: 'carlosdockerregistrie.azurecr.io/latest:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout